version: '3.8'

services:
  gateway:
    volumes:
      - ../gateway:/app
    environment:
      NODE_ENV: development
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      STRAPI_URL: http://strapi:1337

  frontend:
    volumes:
      - ../:/app
    environment:
      NODE_ENV: development
